sudo: false
language: node_js
node_js:
  - 6
  - 7
notification:
  slack:
    secure: "kgrJl00zmy/sJevvs+/ZSn2buAuLtRw++N+JbF2coWYmKPFUEtWAXP+7Y6+AcQWRqzpDxO0o6S5AeQWwZN4WGeD8M0o1CdHiRA90yNW2zJI7OT0J0qd97uyUcxG8gDtbAmyNUZN2JiSu491gswFbHVyYQsvMDzCy7WC063U10wJOMON/HoZnEAz4LgkdFLyGp7W/leXniRT0RcJ7yolG5fE5xJvCPya6NygjveKj+TcMkenPHaVmi9KmKRMlRVNHMJOaXDosdUF9hLK8SFXVjCnqDWLx45cR/N+9f9ljwzYKJiwazGnh4P0JZoLE6w1k0PVtunNouVfZJWinQ3oxxWXQx1m0l7bobaKr0yTtoI9MWhKP3jzR1kDynobJEfNM4Ao1SDRJnlNkOy06HqxsY91bhN34QQrcu1u5S2e7Fkn4FSTMZ32VHVuVody6yGpryBaTZxxXvyZS0MN4J3pXZ277KKK2/1UbRNBmdakcyJIosUVPsruVDMKXWHoG5yEtwa7D+on5A4Cu1/fQGb+9R9zUnxdSUvsT3+960yN5r37ExXJF5SAaj6yunfTe5sgHAL+N8s1xIRfhIVIiEB6a0NRid/DxvmzEamxzVzq5xKwSHK+dG4RCRaNqVHZqPwWUB1G3ldXJrVdZZ0gRTzmTVHMgSCoqpK46W2J9EWHU9jU="
